# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 934d3504aabc1f6a533a19d8ed03eb066fe947e6c9c596854b17dc9e8c440167b804c8b03869b0611f17cf4736d65f8e85527ebf5064d9743e3e35605c8b4d99

test:
  secret_key_base: 5e9e596ae596bec0d25a88f33b994aaf9b8e519b3a769f380ac04591bffb7cdea182181497e37b508cdb25c68eb5136383e64156391a2c1f281f8180f54ceaf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
